### ISSUE TITLE
Quality Control tasks

### ISSUE THREAD

**Issue by setheclark** [cltmobilemeetup/trail-of-history-android#1]
Quality Control items to set up:

* File templates
* Project code style
* Lint settings
* Checkstyle settings
* PMD settings
* Findbugs settings
* Jacoco coverage reporting
* ...

We can tie a lot of these tools together into the 'check' task so that contributors can check their code before submitting a pull request.

**Comment by simplaapliko** [comment]
maybe also copyright template...

**Comment by setheclark** [comment]
This seems like a good guide we could follow.
[https://github.com/bufferapp/android-guidelines/blob/master/project_style_guidelines.md](https://github.com/bufferapp/android-guidelines/blob/master/project_style_guidelines.md)
