### ISSUE TITLE
GPS location for POI

### ISSUE THREAD

**Issue by rdrobinson3** [cltmobilemeetup/trail-of-history-android#12]
When adding or editing a point of interest it would be nice to be able to enter the latitude and longitude for the point of interest. If the location could alternatively be selected from a map that would be really neat. 

On the point of interest detail view it would be cool to see the location on a map.

**Comment by nohe427** [comment]
If we are going the Google Maps route: 

https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMapClickListener
