### ISSUE TITLE
Keep User Logged In

### ISSUE THREAD

**Issue by rdrobinson3** [cltmobilemeetup/trail-of-history-android#6]
After logging into the application if the user leaves the application and returns after the application is killed (by the OS, or manually) they are logged out. We should maintain the sessions indefinitely (as long as Firebase allows).

**Comment by nohe427** [comment]
Based upon this documentation:

The User Lifecycle
https://firebase.google.com/docs/auth/users#the_user_lifecycle

I think that this will maintain the session indefinitely until the user decides to sign out (FirebaseAuth.signOut()) or uninstall the app.  Previously, the default authentication period was 24 hours and was controllable from the console but this sounds like the token is automagically refreshed as needed.
