### ISSUE TITLE
Remember Username

### ISSUE THREAD

**Issue by rdrobinson3** [cltmobilemeetup/trail-of-history-android#7]
It would be nice if there was a checkbox on the login screen to remember the username for subsequent logins.

**Comment by nohe427** [comment]
Is it alright if we use shared preferences for this?

**Comment by OllenDev** [comment]
I don't see any issues with that. Maybe we should look into using https://github.com/firebase/FirebaseUI-Android

**Comment by nohe427** [comment]
Kind of cranked that PR out before I saw this.  I'll take a gander at it.
