### ISSUE TITLE
Convert findViewById to Butterknife.

### ISSUE THREAD

**Issue by rdrobinson3** [cltmobilemeetup/trail-of-history-android#8]
[Butterknife](http://jakewharton.github.io/butterknife/) has been talked about often during the meetup meetings. 

Replacing all of the findViewById calls with Butterknife would reduce boilerplate.

**Comment by OlegKan** [comment]
Would it be fine also to upgrade to butterknife8?

**Comment by OllenDev** [comment]
I think that would be ok.

**Comment by OlegKan** [comment]
pull request #14 has been created
