### ISSUE TITLE
Editing a POI has a strange flow

### ISSUE THREAD

**Issue by rdrobinson3** [cltmobilemeetup/trail-of-history-android#9]
Currently when a POI is edited it takes you to the detail screen with the edited POI name. Hitting back from there takes you to a detail screen for the same point of interest but with the unedited name. Hitting back again to return to the list will show that the value has in fact been updated and is displayed correctly. 

We should modify the edit flow to return to the previous view which displays the updated value.

**Comment by OlegKan** [comment]
Not able to reproduce, probably has been already fixed
